### ISSUE TITLE
exp/textinput crashes on the first Hangul syllable on Windows

### ISSUE THREAD

**Issue by mirusu400** [hajimehoshi/ebiten#3539]
### Ebitengine Version

v2.9.0 (and current main)

### Operating System

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (paste your `go version` output)

go version go1.25.6 windows/amd64

### What steps will reproduce the problem?

1. Build and run the minimal repro attached below
2. Click a text field to focus it.
3. Switch to the Microsoft Korean IME (Hangul mode).
4. Type any syllable, e.g. `가`.

```
module hangul-ime-repro

go 1.25.0

require (
	github.com/hajimehoshi/bitmapfont/v4 v4.0.0
	github.com/hajimehoshi/ebiten/v2 v2.9.0
)
```

`go.mod`

```
package main

import (
	"image"
	"image/color"
	"log"

	"github.com/hajimehoshi/bitmapfont/v4"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/exp/textinput"
	"github.com/hajimehoshi/ebiten/v2/inpututil"
	"github.com/hajimehoshi/ebiten/v2/text/v2"
)

var face = text.NewGoXFace(bitmapfont.FaceEA)

type game struct {
	composer    textinput.Composer
	focused     bool
	committed   string // text the IME has committed
	composition string // live preedit, shown in brackets
}

func newGame() *game {
	g := &game{}
	// Returning options keeps a single IME session open on the window, so
	// Korean keystrokes route straight into the composition path.
	g.composer.OnNewSession = func() *textinput.SessionOptions {
		return &textinput.SessionOptions{
			CaretBounds:     caretBounds(g.committed),
			TextBeforeCaret: g.committed,
		}
	}
	g.composer.OnComposition = func(c *textinput.Composition) {
		g.composition = c.Text()
	}
	g.composer.OnCommit = func(c *textinput.Commit) {
		g.committed += c.Text()
	}
	return g
}

func caretBounds(before string) image.Rectangle {
	x := 20 + int(text.Advance(before, face))
	return image.Rect(x, 20, x+1, 40)
}

func (g *game) Update() error {
	// Start on a click: by then the window is active and the IME can attach.
	if inpututil.IsMouseButtonJustPressed(ebiten.MouseButtonLeft) {
		g.focused = true
	}
	if !g.focused {
		return nil
	}
	_, err := g.composer.Update()
	return err
}

func (g *game) Draw(screen *ebiten.Image) {
	screen.Fill(color.RGBA{0x1e, 0x1e, 0x1e, 0xff})

	op := &text.DrawOptions{}
	op.GeoM.Translate(20, 20)
	op.ColorScale.ScaleWithColor(color.White)
	text.Draw(screen, g.committed+"["+g.composition+"]", face, op)

	msg := "Click to focus, then type with the Korean IME."
	if g.focused {
		msg = "Focused. Switch to the Korean IME and type. Unpatched build crashes."
	}
	hint := &text.DrawOptions{}
	hint.GeoM.Translate(20, 70)
	hint.ColorScale.ScaleWithColor(color.RGBA{0x99, 0x99, 0x99, 0xff})
	text.Draw(screen, msg, face, hint)
}

func (g *game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return 640, 200
}

func main() {
	ebiten.SetWindowTitle("Hangul IME crash repro (exp/textinput)")
	ebiten.SetWindowSize(640, 200)
	if err := ebiten.RunGame(newGame()); err != nil {
		log.Fatal(err)
	}
}
```

main.go

### What is the expected result?

The syllable is composed as a preedit and committed, the same as with the Japanese IME or any other IME.

### What happens instead?

It just crashes.

sample traceback:
```
C:\Users\OWNER\Documents\_hacking\_aram_proj\hangul-ime-repro\hangul-ime-BEFORE-crash.exe
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/exp/textinput.(*textInputImpl).update(0x7ff675867a20)
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/exp/textinput/textinput_windows.go:261 +0x51b
github.com/hajimehoshi/ebiten/v2/exp/textinput.(*textInputImpl).wndProc(0x7ff675867a20, 0x31ac2, 0x4f5408?, 0x3141, 0x6018)
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/exp/textinput/textinput_windows.go:161 +0x250
syscall.SyscallN(0xc001702370?, {0xc001702378?, 0x0?, 0x0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:500 +0x1e
golang.org/x/sys/windows.(*Proc).Call(0x7ff674d5ab65?, {0xc001702378?, 0x7ff675171360?, 0x1?})
        C:/Users/OWNER/go/pkg/mod/golang.org/x/sys@v0.47.0/windows/dll_windows.go:166 +0x1c
golang.org/x/sys/windows.(*LazyProc).Call(0x7ff675862660, {0xc001702378, 0x1, 0x1})
        C:/Users/OWNER/go/pkg/mod/golang.org/x/sys@v0.47.0/windows/dll_windows.go:316 +0x4a
github.com/hajimehoshi/ebiten/v2/internal/glfw._DispatchMessageW(...)
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/internal/glfw/api_windows.go:1056
github.com/hajimehoshi/ebiten/v2/internal/glfw.platformPollEvents()
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/internal/glfw/win32_window_windows.go:2230 +0x165
github.com/hajimehoshi/ebiten/v2/internal/glfw.PollEvents(...)
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/internal/glfw/window.go:887
github.com/hajimehoshi/ebiten/v2/internal/ui.(*glfwBackend).update(0xc000108a88)
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/internal/ui/ui_glfw.go:1245 +0x16f
github.com/hajimehoshi/ebiten/v2/internal/ui.(*glfwBackend).updateGame.func1()
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/internal/ui/ui_glfw.go:1377 +0x133
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).loop.func1({0xc000fc2190?, 0xc000fc0d90?})
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/internal/thread/thread.go:85 +0x58
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).loop(0xc00069c008, {0x7ff675530458, 0xc00068e0f0})
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/internal/thread/thread.go:86 +0x3b
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc00069c008, {0x7ff675530458, 0xc00068e0f0})
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/internal/thread/thread.go:62 +0x5d
github.com/hajimehoshi/ebiten/v2/internal/ui.(*glfwBackend).runMultiThread(0xc000108a88, {0x7ff675533380, 0xc000692070}, 0xc000692000)
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/internal/ui/ui_glfw.go:2208 +0x2ec
github.com/hajimehoshi/ebiten/v2/internal/ui.(*glfwBackend).run(0xc0006a4d80?, {0x7ff675533380?, 0xc000692070?}, 0x7ff674d5ab65?)
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/internal/ui/ui_glfw.go:2165 +0x30
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).Run(0xc0006a4d80, {0x7ff675533380, 0xc000692070}, 0xc000692000)
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/internal/ui/ui_desktop.go:138 +0x8c
github.com/hajimehoshi/ebiten/v2.RunGameWithOptions({0x7ff67552ef50, 0xc00068e050}, 0xc00002a0d8?)
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/run.go:378 +0xfe
github.com/hajimehoshi/ebiten/v2.RunGame(...)
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/ebiten-before/run.go:240
main.main()
        C:/Users/OWNER/AppData/Local/Temp/claude/C--Users-OWNER-Documents--hacking--aram-proj-ebiten/bb759361-351a-44fc-b710-0319f6f765fb/scratchpad/build-before/main.go:105 +0x12e
```

### Anything else you feel useful to add?

I have a fix ready and will open a PR referencing this issue.

**Comment by hajimehoshi** [comment]
> v2.9.0 (and current main)

Could you tell me the exact commit? Composer should not work with v2.9 btw

**Comment by hajimehoshi** [comment]
Or, if there is a reproducible code with v2.9, please tell me: I'll take this issue as a serious bug and backport the fix to v2.9. Thanks,

**Comment by mirusu400** [comment]
Hello @hajimehoshi , I already wrote reproducible code and video in both my Issue and PR (#3540).

You might need Korean IME or Korean VM, So the test might be hard..  Feel free to comment it and I'll surely test anything

**Comment by hajimehoshi** [comment]
> I already wrote reproducible code

The code is not compilable with v2.9, but you reported this issue was reproduced with v2.9. Do you have a reproducible case for v2.9?

```
% GOOS=windows GOARCH=amd64 go build .
# hangul-ime-repro
./main.go:19:24: undefined: textinput.Composer
./main.go:29:46: undefined: textinput.SessionOptions
./main.go:30:21: undefined: textinput.SessionOptions
./main.go:35:47: undefined: textinput.Composition
./main.go:38:42: undefined: textinput.Commit
```

**Comment by mirusu400** [comment]
https://github.com/user-attachments/assets/f5c63602-2b0a-4a18-806b-3870d5d68bef

I dont know the reason, but I can test on my machine..

**Comment by hajimehoshi** [comment]
> I dont know the reason, but I can test on my machine..

It's because you are using go.work which specifies the latest Ebitengine, not 2.9.

**Comment by mirusu400** [comment]
> > I dont know the reason, but I can test on my machine..
> 
> It's because you are using go.work which specifies the latest Ebitengine, not 2.9.

Oh I didnt realize that :eyes: I will give you latest test code

**Comment by mirusu400** [comment]
[hangul-ime-repro-v29.zip](https://github.com/user-attachments/files/31525107/hangul-ime-repro-v29.zip)
