### ISSUE TITLE
"unexpected '@' in program" running examples on macOS

### ISSUE THREAD

**Issue by lucymhdavies** [hajimehoshi/ebiten#781]
On macOS 10.11.6 (El Capitan), with the latest ebiten from the master branch:

```
~/go/src/github.com/hajimehoshi/ebiten/examples/sprites [master|✔]
14:18 $ go run main.go
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
ca.m:49:7: error: unexpected '@' in program
ca.m:54:13: warning: instance method '-setMaximumDrawableCount:' not found (return type defaults to 'id') [-Wobjc-method-access]
/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:44:12: note: receiver is instance of class declared here
ca.m:65:7: error: unexpected '@' in program
ca.m:68:37: warning: instance method '-setDisplaySyncEnabled:' not found (return type defaults to 'id') [-Wobjc-method-access]
/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:44:12: note: receiver is instance of class declared here
```

Not sure if this is a bug with ebiten, or if I'm just on too old a version of macOS now you're using Metal for rendering.

Works fine with latest release (v1.8.1).

**Comment by hajimehoshi** [comment]
OK so probably you are using a pre-installed gcc, which might be old. What would `/usr/bin/xcodebuild -version` say?

You can install Xcode by `xcode-select --install` but this might take some long time.

https://www.ics.uci.edu/~pattis/common/handouts/macclion/clang.html

**Comment by lucymhdavies** [comment]
```
$ /usr/bin/xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

Could be an old gcc. I don't think I've ever needed it in the 3 or so years I've had this machine, so I'd never have updated it myself.

```
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by hajimehoshi** [comment]
Hmm, ok.

The cause is the usages of `@available` syntax.

https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/marking_api_availability_in_objective-c

I'm thinking to avoid this by macro. Please stay tuned (it's also ok if you want to update macOS or Xcode now).

**Comment by lucymhdavies** [comment]
Cool. 👍 

It's no big deal for me at the moment anyway. This is my work laptop (hence the old macOS that I can't update 😢), and it does work fine on my personal laptop, which has the latest macOS.

For my purposes, locking this laptop's version of ebiten to v1.8.1 works for now.

**Comment by hajimehoshi** [comment]
```
$ /usr/bin/xcodebuild -version
```

What about `xcodebuild -version`? Thanks!

**Comment by lucymhdavies** [comment]
```
$ /usr/bin/xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

Guess I must have installed them independently of xcode

**Comment by hajimehoshi** [comment]
I mean, what plain `xcodebuild -version` would say, instead of `/usr/bin/xcodebuild -version`.

**Comment by hajimehoshi** [comment]
Could you update your Ebiten and try it again? Thanks!

**Comment by lucymhdavies** [comment]
```
~/go/src/github.com/hajimehoshi/ebiten/examples/sprites [master|✔]
15:36 $ git pull
Updating 802f3cfe..72c1a73c
Fast-forward
 internal/graphicsdriver/metal/ca/ca.go |  5 ++++-
 internal/graphicsdriver/metal/ca/ca.m  | 36 ++++++++++++++++++++++--------------
 2 files changed, 26 insertions(+), 15 deletions(-)

~/go/src/github.com/hajimehoshi/ebiten/examples/sprites [master|✔]
15:36 $ go run main.go
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
ca.m:59:11: warning: instance method '-setMaximumDrawableCount:' not found (return type defaults to 'id') [-Wobjc-method-access]
/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:44:12: note: receiver is instance of class declared here
ca.m:77:35: warning: instance method '-setDisplaySyncEnabled:' not found (return type defaults to 'id') [-Wobjc-method-access]
/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:44:12: note: receiver is instance of class declared here
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
# github.com/hajimehoshi/ebiten
../../run.go:25:9: undefined: __EBITEN_REQUIRES_GO_VERSION_1_11_OR_LATER__
```

**Comment by hajimehoshi** [comment]
> `__EBITEN_REQUIRES_GO_VERSION_1_11_OR_LATER__`

This means that you should use Go 1.11 or later :-)

**Comment by lucymhdavies** [comment]
Huh. Thought I just updated that. Let me actually update properly and try again.

**Comment by lucymhdavies** [comment]
```
~/go/src/github.com/hajimehoshi/ebiten/examples/sprites [master|✔]
15:57 $ go version
go version go1.11.4 darwin/amd64

~/go/src/github.com/hajimehoshi/ebiten/examples/sprites [master|✔]
15:57 $ go run main.go
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
ca.m:59:11: warning: instance method '-setMaximumDrawableCount:' not found (return type defaults to 'id') [-Wobjc-method-access]
/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:44:12: note: receiver is instance of class declared here
ca.m:77:35: warning: instance method '-setDisplaySyncEnabled:' not found (return type defaults to 'id') [-Wobjc-method-access]
/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:44:12: note: receiver is instance of class declared here
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
```

<img width="754" alt="screen shot 2019-01-11 at 15 59 29" src="https://user-images.githubusercontent.com/1116529/51044800-e795d480-15b9-11e9-8427-e6836f7679d9.png">

**Comment by hajimehoshi** [comment]
Hmmm, that's unfortunate, I have no idea what is going on.

Another idea is to force to use OpenGL instead of Metal in such old macOS environment. Let me think... 🤔

**Comment by lucymhdavies** [comment]
That sounds like a reasonable compromise; you can't support older versions of macOS forever.

**Comment by hajimehoshi** [comment]
Thank you for confirming!

Fixed to use OpenGL when macOS is 10.11 or older. (We have already confirmed that Metal worked on macOS 10.12 or newer).

**Comment by lucymhdavies** [comment]
Yep. Confirmed that this does work :)

<img width="705" alt="screen shot 2019-01-11 at 16 33 42" src="https://user-images.githubusercontent.com/1116529/51046708-b7046980-15be-11e9-91d9-e904538cd6b8.png">

We do still get the warnings as before, but thats less important than the main thing, which is that it works 🎉 

```
~/go/src/github.com/hajimehoshi/ebiten/examples/life [master|✔]
16:32 $ git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/hajimehoshi/ebiten
   72c1a73c..dc0c6e09  master     -> origin/master
Updating 72c1a73c..dc0c6e09
Fast-forward
 internal/graphicscommand/driver_mac.go | 28 ++++++++++++++++++++++++----
 1 file changed, 24 insertions(+), 4 deletions(-)

~/go/src/github.com/hajimehoshi/ebiten/examples/life [master|✔]
16:32 $ go run main.go
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
ca.m:59:11: warning: instance method '-setMaximumDrawableCount:' not found (return type defaults to 'id') [-Wobjc-method-access]
/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:44:12: note: receiver is instance of class declared here
ca.m:77:35: warning: instance method '-setDisplaySyncEnabled:' not found (return type defaults to 'id') [-Wobjc-method-access]
/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:44:12: note: receiver is instance of class declared here
# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
```

**Comment by hajimehoshi** [comment]
Yeees! It would be impossible to remove all the warning, but I think that's acceptable.

Thank you for cooperation!

**Comment by lucymhdavies** [comment]
Yep.  It's a build warning anyway, so a compiled app throws no errors.
